services:
  database:
    build:
      context: ./DB VM
    container_name: db-vm
    ports:
      - "8081:80"
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=27017
      - MONGO_DB_NAME=employees_DB
      # Optional authentication - uncomment if needed
      # - MONGO_USERNAME=admin
      # - MONGO_PASSWORD=secret
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "/home/app/employee_db/healthcheck.sh"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s

  app:
    build:
      context: ./App VM
    container_name: app-vm
    ports:
      - "8080:80"
    environment:
      - DB_HOST=database
      - DB_PORT=80
      - API_PROTOCOL=http
      - DB_EXTERNAL_HOST=localhost
      - DB_EXTERNAL_PORT=8081
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: 