name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get changed directories
      id: changed-dirs
      run: |
        BASE_SHA=${{ github.event.before }}
        HEAD_SHA=${{ github.sha }}
        
        CHANGED_DIRECTORIES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -v "\." | sort -u || true)
        echo "Detected changes in: $CHANGED_DIRECTORIES"
        
        if echo "$CHANGED_DIRECTORIES" | grep -q "App VM"; then
          echo "CHANGED_APP=true" >> $GITHUB_ENV
        else
          echo "CHANGED_APP=false" >> $GITHUB_ENV
        fi
        
        if echo "$CHANGED_DIRECTORIES" | grep -q "DB VM"; then
          echo "CHANGED_DB=true" >> $GITHUB_ENV
        else
          echo "CHANGED_DB=false" >> $GITHUB_ENV
        fi
    
    - name: Generate timestamp
      id: timestamp
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push App VM image
      if: env.CHANGED_APP == 'true'
      uses: docker/build-push-action@v4
      with:
        context: "./App VM"
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/app-image:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/app-image:${{ env.TIMESTAMP }}
    
    - name: Build and push DB VM image
      if: env.CHANGED_DB == 'true'
      uses: docker/build-push-action@v4
      with:
        context: "./DB VM"
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/db-image:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/db-image:${{ env.TIMESTAMP }}

