name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-dirs.outputs.dirs }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get changed directories
      id: changed-dirs
      run: |
        BASE_SHA=${{ github.event.before }}
        HEAD_SHA=${{ github.sha }}
        
        CHANGED_DIRECTORIES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -v "\." | sort -u || true)
        echo "CHANGED_DIRECTORIES=$CHANGED_DIRECTORIES" >> $GITHUB_ENV
        echo "dirs=$CHANGED_DIRECTORIES" >> $GITHUB_OUTPUT
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and tag Docker images for App VM
      if: contains(steps.changed-dirs.outputs.dirs, 'App VM')
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        cd "App VM"
        docker build . --file Dockerfile \
          --tag app-image:$SHORT_SHA
    
    - name: Build and tag Docker images for DB VM
      if: contains(steps.changed-dirs.outputs.dirs, 'DB VM')
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        cd "DB VM"
        docker build . --file Dockerfile \
          --tag db-image:$SHORT_SHA

  push_to_dockerhub:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push App VM image
      if: contains(needs.build.outputs.dirs, 'App VM')
      uses: docker/build-push-action@v4
      with:
        context: "./App VM"
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/app-image:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/app-image:${{ github.sha }}
    
    - name: Build and push DB VM image
      if: contains(needs.build.outputs.dirs, 'DB VM')
      uses: docker/build-push-action@v4
      with:
        context: "./DB VM"
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/db-image:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/db-image:${{ github.sha }}

